### ISSUE TITLE
Fix tooltip component

### ISSUE THREAD

**Issue by Schwartz10** [glifio/react-components#175]
<img width="401" alt="image" src="https://user-images.githubusercontent.com/12353734/155188038-8b290cb0-f27e-4c03-966e-ed7d4e6c7bde.png">

Not sure where this got all weird on us. Also @navFooh check the hover behavior out (lol)

**Comment by navFooh** [comment]
For the admin page I think it's nice to just show the extra information in a subheader, since there is more than enough space. Then we can remove the Toolip altogether since it's not used anywhere else.

Let me know what you think, if you prefer a tooltip button, or to have one if we need it in the future, I can fix it

![image](https://user-images.githubusercontent.com/394452/157052209-1fdde8b0-8b95-4b26-bca3-f7e6b4075513.png)
