### ISSUE TITLE
Transactions can get sent when the "Total" is greater than the signers balance

### ISSUE THREAD

**Issue by Schwartz10** [glifio/react-components#370]
1. Go to the wallet 
2. Use an account with a low balance, e.g. `.500001 FIL`
3. Try to send `.5 FIL`
4. The total amount when in review phase says like: `5.01.. FIL` (which is greater than the balance in step 2)
5. Send the transaction 

I'd expect to see an error that says the user can't afford this transaction, yet the transaction goes through anyway?

**Comment by navFooh** [comment]
When trying this I do get an error from the gas estimation before being able to send the transaction:

![image](https://user-images.githubusercontent.com/394452/174633626-8e51fd96-30c1-478c-961e-ad1cb3521f85.png)

However I do agree we should add another failsafe in place, since it's easy to catch this
